apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-bot-api
  labels:
    app: mp-bot-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mp-bot-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mp-bot-api
    spec:
      containers:
        - name: mp-bot-api
          image: cr.selcloud.ru/dockerhub/simple-backend:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 4200
      imagePullSecrets:
        - name: regcred
