apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-backend-deployment
  labels:
    app: simple-backend-deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-backend-pod-label
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        rollme: { { randAlphaNum 5 | quote } }
      labels:
        app: simple-backend-pod-label
    spec:
      containers:
        - name: simple-backend
          image: cr.selcloud.ru/dockerhub/simple-backend:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db-host
                  name: db-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: db-port
                  name: db-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: db-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: db-secret
            - name: FS_LOGIN
              valueFrom:
                secretKeyRef:
                  key: fs-login
                  name: fs-secret
            - name: FS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: fs-password
                  name: fs-secret
      imagePullSecrets:
        - name: regcred
