apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-backend-pod
  labels:
    app: mp-bot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-bot-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mp-bot-api
    spec:
      containers:
        - name: simple-backend
          image: cr.selcloud.ru/dockerhub/simple-backend:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
