apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-backend-deployment
  labels:
    app: simple-backend-deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-backend-deployment-label
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-backend-deployment-label
    spec:
      containers:
        - name: simple-backend
          image: cr.selcloud.ru/dockerhub/simple-backend:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: regcred
