apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5M"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "5M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
    - hosts:
        - api2.wb-bot.fun
      secretName: mp-bot-tls-secret
  rules:
    - host: "api2.wb-bot.fun"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: simple-backend-service
                port:
                  number: 3000

  ingressClassName: nginx

---


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mp-bot-le-crt
spec:
  secretName: mp-bot-tls-secret
  issuerRef:
    kind: Issuer
    name: mp-bot-letsencrypt
  commonName: api2.wb-bot.fun
  dnsNames:
    - api2.wb-bot.fun

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mp-bot-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: mp-bot-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx

---
